# Generated by Django 3.0.2 on 2020-02-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('PathernalLastName', models.CharField(blank=True, max_length=100)),
                ('MathernalLastName', models.CharField(blank=True, max_length=100)),
                ('Edad', models.IntegerField(blank=True, default=0)),
                ('Cedula', models.CharField(blank=True, max_length=20)),
                ('Sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='email',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='email',
            name='persona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Persona'),
            preserve_default=False,
        ),
    ]
